HISTSIZE=50000
SAVEHIST=50000
HISTFILE=~/.cache/zsh/history
setopt HIST_IGNORE_DUPS HIST_IGNORE_SPACE SHARE_HISTORY HIST_EXPIRE_DUPS_FIRST HIST_FIND_NO_DUPS \
       HIST_SAVE_NO_DUPS HIST_REDUCE_BLANKS HIST_VERIFY EXTENDED_HISTORY
